
name: "Pose Detection Camera"
description: "Pose detection camera stream using MediaPipe and OpenCV."
version: "1.1.8"
slug: "pose_camera"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
option:

devices:
  - "/dev/video0:/dev/video0:rwm"
  - "/dev/video1:/dev/video1:rwm"
  - "/dev/video2:/dev/video2:rwm"
  - "/dev/video3:/dev/video3:rwm"
startup: services
ports:
  8000/tcp: 8000
